[package]
name = "retry-cli"
version = "0.1.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies
[dependencies]

[dependencies.retry]
version = "1.3.0"
default-features = false

[[bin]]
name = "retry"
path = "src/main.rs"
